fuge_global:
  tail: true
  monitor: false
  auto_generate_environment: false
  monitor_excludes:
    - '**/node_modules/**'
    - '**/.git/**'
    - '**/*.log'
bases:
  type: process
  path: ../../bases-service
  run: ts-node service.ts
apigateway:
  type: process
  path: ../../api-gateway
  run: ts-node main.ts
ping:
  type: process
  path: ../../ping-service
  run: ts-node service.ts
repl:
  type: process
  path: ../../repl
  run: ts-node repl.ts