version: '3'

networks:
  trifacta:
    driver: overlay

services:
  bases:
    image: vforv/bases:v1
    networks:
        - trifacta
    environment:
      HOST: bases
      REGISTRY: consul
    command: bash -c "cd bases-service && npm start"
  api:
    image: vforv/api-gateway:v1
    ports:
        - "5000:5000"
    networks:
        - trifacta
    environment:
      HOST:  api
      BASES: bases
      REGISTRY: consul
    command: bash -c "cd api-gateway && npm start"
  ping:
    image: vforv/ping-service:v1
    networks:
        - trifacta
    environment:
      HOST:  ping
      BASES: bases
      REGISTRY: consul
    command: bash -c "cd ping-service && npm start"
  consul:
    image: sdelrio/consul
    networks:
        - trifacta
    ports:
        - "8500:8500"
    environment:
      HOST:  ping
      BASES: bases
      CONSUL: consul
      CONSUL_BIND_INTERFACE: consul
    deploy:
        replicas: 3
        placement:
            constraints: [node.role == manager]
        resources:
            reservations:
                memory: 128M
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
        update_config:
            parallelism: 1
            delay: 10s
            failure_action: continue
