version: '3'

networks:
  trifacta:
    driver: overlay

services:
  bases:
    image: vforv/bases:v1
    networks:
      trifacta:
        aliases: 
          - bases
    environment:
      PORT: 39000
      HOST: bases
      BASES: bases:39000
    command: bash -c "cd bases-service && npm start"
  api:
    image: vforv/api-gateway:v1
    ports:
        - "5000:5000"
    networks:
        - trifacta
    environment:
      HOST: '@eth0'
      BASES: bases:39000
    command: bash -c "cd api-gateway && npm start"
  ping:
    image: vforv/ping-service:v1
    networks:
        - trifacta
    environment:
      HOST: '@eth0'
      BASES: bases:39000
    command: bash -c "cd ping-service && npm start"