version: '3'
services:
  bases:
    image: vforv/bases:v1
    command: bash -c "cd bases-service && npm start"
    network_mode: "host"
  api:
    image: vforv/api-gateway:v1
    ports:
        - "5000:5000"
    command: bash -c "cd api-gateway && npm start"
    network_mode: "host"
  ping:
    image: vforv/ping-service:v1
    command: bash -c "cd ping-service && npm start"
    network_mode: "host"
