version: '3'

networks:
  trifacta:
    driver: overlay

services:
  consul:
    image: sdelrio/consul${TAG}
    labels: [app=consul]
    ports:
        - "8500:8500"
    networks:
        - trifacta
    environment:
        - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
        - CONSUL_BIND_INTERFACE=eth0
        - CONSUL=consul
        - CONSUL_CHECK_LEADER=true
    deploy:
        replicas: 3
        placement:
            constraints: [node.role == manager]
        resources:
            reservations:
                memory: 128M
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
        update_config:
            parallelism: 1
            delay: 10s
            failure_action: continue
  bases:
    image: vforv/bases:v2
    networks:
        - trifacta
    environment:
      HOST: bases
      REGISTRY: consul
    command: bash -c "cd bases-service && npm start"
  api:
    image: vforv/api-gateway:v2
    ports:
        - "5000:5000"
    networks:
        - trifacta
    environment:
      HOST:  api
      BASES: bases
      REGISTRY: consul
    command: bash -c "cd api-gateway && npm start"
  ping:
    image: vforv/ping-service:v2
    networks:
        - trifacta
    environment:
      HOST:  ping
      BASES: bases
      REGISTRY: consul
    command: bash -c "cd ping-service && npm start"
  