version: '3'

networks:
  trifacta:
    driver: overlay

services:
  bases:
    image: vforv/bases:v1
    networks:
        - trifacta
  api:
    image: vforv/api-gateway:v1
    ports:
        - "5000:5000"
    networks:
        - trifacta
  ping:
    image: vforv/ping-service:v1
    networks:
        - trifacta
